# Generated by Django 3.1.3 on 2020-11-22 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_linked_in_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'unique': 'The username is already taken.'}, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$', 'Enter a valid username. This value may contain only letters, numbers and _ character.', 'invalid')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(error_messages={'unique': 'The username is already taken.'}, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$', 'Enter a valid username. This value may contain only letters, numbers and _ character.', 'invalid')]),
        ),
    ]
